services:

  postgres:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example
    restart: on-failure
    healthcheck:
      test: pg_isready -U example
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
