[project]
classifiers = [
  "Private :: Do Not Upload",
]
dependencies = [
  "alembic>=1.18.4",
  "pydantic-settings>=2.14.1",
  "sqlalchemy>=2.0.41",
]
description = "Example project to test pytest-sqlalchemy-alembic plugin"
name = "example-project"
requires-python = ">=3.10"
version = "0.1.0"

[project.optional-dependencies]
postgres = [
  "psycopg2>=2.9.12",
]

[dependency-groups]
dev = [
  "mypy>=2.1.0",
  "pytest>=9.0.3",
  "pytest-sqlalchemy-alembic>=0.1.0",
]

[tool.uv.sources]
pytest-sqlalchemy-alembic = {path = "../"}

[tool.pytest.ini_options]
sqlalchemy_session_maker = "example_project.db:SessionLocal"

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
plugins = ["pydantic.mypy"]
strict_equality = true
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
