[project]
classifiers = [
  "Private :: Do Not Upload",
]
dependencies = [
  "alembic>=1.18.4",
  "pydantic-settings>=2.14.1",
  "sqlalchemy>=2.0.41",
]
description = "Example project to test pytest-sqlalchemy-alembic plugin"
name = "example-project"
requires-python = ">=3.10"
version = "0.1.0"

[project.optional-dependencies]
postgres = [
  "pg8000>=1.31.5",
  "psycopg>=3.3.4",
  "psycopg2>=2.9.12",
  "psycopg2cffi>=2.9.0",
]
sqlite = [
    "sqlcipher3>=0.6.2",
]
mariadb = [
    "cymysql>=1.1.1",
    "mariadb>=1.1.14",
    "mysql-connector-python>=9.7.0",
    "mysqlclient>=2.2.8",
    "pymysql>=1.2.0",
]

[dependency-groups]
dev = [
  "ipython>=8.39.0",
  "mypy>=2.1.0",
  "pytest>=9.0.3",
  "pytest-sqlalchemy-alembic>=0.1.0",
]

[tool.uv]
reinstall-package = ["pytest-sqlalchemy-alembic"]

[tool.uv.sources]
pytest-sqlalchemy-alembic = {path = "../"}

[tool.pytest.ini_options]
sqlalchemy_session_maker = "example_project.db:SessionLocal"

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
plugins = ["pydantic.mypy"]
strict_equality = true
warn_no_return = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
