name: "CI"

on:
  pull_request:

jobs:
  dialect-sqlite:
    uses: ./.github/workflows/dialect-sqlite.yml
    secrets: inherit

  dialect-postgresql:
    uses: ./.github/workflows/dialect-postgresql.yml
    secrets: inherit

  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Ruff check
        run: uv run ruff check .

      - name: Check imports sorting
        run: uv run ruff check --select I .

      - name: Ruff check formatting
        run: uv run ruff format --check .

      - name: Load mypy cache
        uses: actions/cache@v5
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}

      - name: Mypy (plugin)
        run: uv run mypy .

      - name: Mypy (Example project)
        working-directory: example_project
        run: uv run mypy .

  plugin-tests:
    name: Plugin tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        dependencies:
          - "--resolution highest"
          - "--resolution lowest-direct"

          # Below are the most popular package versions according PyPI stats
          - "--with alembic==1.18.4"
          - "--with pytest==8.4.1"
          - "--with sqlalchemy==2.0.41"

        include:
          # Checking sqlalchemy bug fix (https://github.com/sqlalchemy/sqlalchemy/issues/11334)
          - python_version: "3.13"
            dependencies: "--with sqlalchemy==2.0.31"
          - python_version: "3.14"
            dependencies: "--with sqlalchemy==2.0.31"

          # Checking sqlalchemy deprecation warning gone
          - python_version: "3.12"
            dependencies: "--with sqlalchemy==2.0.16"

        exclude:
          # Due to bug in sqlalchemy<3.0.31 (https://github.com/sqlalchemy/sqlalchemy/issues/11334)
          - python_version: "3.13"
            dependencies: "--resolution lowest-direct"
          - python_version: "3.14"
            dependencies: "--resolution lowest-direct"

          # Due to a deprecation warning in sqlalchemy<2.0.16 in python>=3.12
          - python_version: "3.12"
            dependencies: "--resolution lowest-direct"

    env:
      UV_PYTHON: ${{ matrix.python_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true

      - name: Run tests
        run: uv run ${{ matrix.dependencies }} pytest
