name: "MySQL dialect tests"

on:
  workflow_call:

jobs:
  dialect-mysql-tests:
    name: Dialect tests (MySQL)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        mysql_version: ["8.0", "8.4", "9.0"]
        drivername: ["mysql+mysqldb", "mysql+pymysql", "mysql+mysqlconnector", "mysql+cymysql"]

    services:
      mysql:
        image: mysql:${{ matrix.mysql_version }}
        env:
          MYSQL_DATABASE: example
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd "healthcheck.sh --connect --innodb_initialized"
          --health-start-period 10s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    env:
      UV_PYTHON: ${{ matrix.python_version }}
      DATABASE_URL: ${{ matrix.drivername }}://root:password@localhost:3306/example

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          cache-suffix: mariadb-${{ matrix.python_version }}

      - name: Run example project tests
        working-directory: example_project
        run: uv run --extra mariadb pytest
